import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

// Autogenerated from the user's uploaded files
const MEDIA_ITEMS = [
  // --- VIDEOS ---
  { type: 'video', src: '/media/videos/VID_20260501_233122_447.mp4' },
  { type: 'video', src: '/media/videos/VID_20260501_234902_177.mp4' },
  { type: 'video', src: '/media/videos/Snapchat-1142346360.mp4' },
  { type: 'video', src: '/media/videos/VID_20260501_014741_976.mp4' },
  { type: 'video', src: '/media/images/justt.zainnn_20260424_230025_736.mp4' },

  // --- IMAGES ---
  { type: 'image', src: '/media/images/IMG20260507140216.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140218.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140219.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140248.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140251.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140253.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140254.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140300.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140306.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140311.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140313.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140434.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140437.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140438.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140439.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140440.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140649.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140651.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140652.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140654.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140656.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140658.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140705.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140706.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140709.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140712.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140715.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140719.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140720.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140721.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140724.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140725.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140727_01.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140735.jpg' },
  { type: 'image', src: '/media/images/IMG20260507140742.jpg' },
  { type: 'image', src: '/media/images/IMG20260507141338.jpg' },
  { type: 'image', src: '/media/images/IMG20260507142328.jpg' },
  { type: 'image', src: '/media/images/IMG20260507142334.jpg' },
  { type: 'image', src: '/media/images/IMG20260507142346.jpg' },
  { type: 'image', src: '/media/images/IMG20260507142352.jpg' },
  { type: 'image', src: '/media/images/IMG20260507142401.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122841.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122844.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122850.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122855.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122901.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122903.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122906.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122908.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122930.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122931.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122939.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122940.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122944.jpg' },
  { type: 'image', src: '/media/images/IMG20260525122950.jpg' },
  { type: 'image', src: '/media/images/IMG20260525123042.jpg' },
  { type: 'image', src: '/media/images/IMG20260525123044.jpg' },
  { type: 'image', src: '/media/images/IMG_20260422_145524_0738.jpg' },
  { type: 'image', src: '/media/images/IMG_20260502_130913.jpg' },
  { type: 'image', src: '/media/images/IMG_20260502_130931.jpg' },
  { type: 'image', src: '/media/images/IMG_20260511_122441_0126.jpg' },
  { type: 'image', src: '/media/images/IMG_20260511_122443_0230.jpg' },
  { type: 'image', src: '/media/images/IMG_20260511_122610_0273.jpg' },
  { type: 'image', src: '/media/images/IMG_20260511_122612_0911.jpg' },
  { type: 'image', src: '/media/images/IMG_20260511_122614_0663.jpg' },
  { type: 'image', src: '/media/images/IMG_20260520_223804_0516.jpg' },
  { type: 'image', src: '/media/images/IMG_20260520_223900.jpg' },
  { type: 'image', src: '/media/images/Screenshot_2026-04-30-23-10-53-34_8c9f6584ca98fa3eab4829abe86aac46.jpg' },
  { type: 'image', src: '/media/images/Snapchat-1024538341.jpg' },
  { type: 'image', src: '/media/images/Snapchat-1160375721.jpg' },
  { type: 'image', src: '/media/images/Snapchat-1256878542.jpg' },
  { type: 'image', src: '/media/images/Snapchat-1983812586.jpg' },
  { type: 'image', src: '/media/images/Snapchat-845288470.jpg' },
  { type: 'image', src: '/media/images/justt.zainnn-20260430-0001.jpg' },
  { type: 'image', src: '/media/images/justt.zainnn_20260422_204147_296.jpg' },
  { type: 'image', src: '/media/images/justt.zainnn_20260423_184307_955.jpg' },
  { type: 'image', src: '/media/images/justt.zainnn_20260423_184311_418.jpg' },
  { type: 'image', src: '/media/images/justt.zainnn_20260426_154546_382.jpg' },
  { type: 'image', src: '/media/images/justt.zainnn_20260427_170505_785.jpg' }
];

export default function CinemaOfUs() {
  const [isOpen, setIsOpen] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  return (
    <div className="relative flex items-center justify-center min-h-screen bg-[#111]">
      <AnimatePresence>
        {!isOpen && (
          <motion.div
            className="relative flex items-center justify-center cursor-pointer z-10"
            onHoverStart={() => setIsHovered(true)}
            onHoverEnd={() => setIsHovered(false)}
            onClick={() => setIsOpen(true)}
            animate={{ y: ["-12px", "12px"] }}
            transition={{
              y: { duration: 3.5, repeat: Infinity, repeatType: "mirror", ease: "easeInOut" }
            }}
          >
            <motion.div
              layoutId="lens-overlay"
              className="w-28 h-28 rounded-full bg-[#550000] shadow-[0_0_40px_rgba(85,0,0,0.9)] border border-[#881111]/60 flex items-center justify-center z-10"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <motion.div 
                 className="text-[#E8DCC4] opacity-80"
                 animate={{ opacity: isHovered ? 1 : 0.6 }}
              >
                <svg width="28" height="28" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M8 5v14l11-7z" />
                </svg>
              </motion.div>
            </motion.div>
            
            <AnimatePresence>
              {isHovered && (
                <motion.div
                  initial={{ opacity: 0, rotate: -45, scale: 0.95 }}
                  animate={{ opacity: 1, rotate: 0, scale: 1 }}
                  exit={{ opacity: 0, rotate: 45, scale: 0.95 }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                  className="absolute w-[120px] h-[120px] md:w-[170px] md:h-[170px] pointer-events-none"
                >
                  <svg viewBox="0 0 100 100" className="w-full h-full overflow-visible animate-[spin_20s_linear_infinite]">
                    <defs>
                      <path id="lensTextPath" d="M 50, 50 m -40, 0 a 40,40 0 1,1 80,0 a 40,40 0 1,1 -80,0" />
                    </defs>
                    <text fontSize="7.2" className="uppercase tracking-[0.24em] fill-[#E8DCC4] font-serif opacity-75">
                      <textPath href="#lensTextPath" startOffset="0%">
                        A MOVEMENT FROZEN IN TIME
                      </textPath>
                    </text>
                  </svg>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {isOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center pointer-events-auto">
            <motion.div
              layoutId="lens-overlay"
              className="absolute inset-0 bg-[#550000]/95 backdrop-blur-xl"
              transition={{ type: "spring", damping: 25, stiffness: 120 }}
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              transition={{ delay: 0.25, duration: 0.8, ease: "easeOut" }}
              className="relative z-10 w-full max-w-lg md:max-w-4xl h-[85vh] rounded-[2.5rem] md:rounded-[3rem] overflow-hidden shadow-[0_0_80px_rgba(0,0,0,0.6)] border border-[#881111]/30 p-2 bg-[#330000]/40 mx-4"
            >
              <div className="w-full h-full rounded-[2.5rem] overflow-hidden relative shadow-[inset_0_0_30px_rgba(0,0,0,0.8)]">
                 <MediaPlayer onClose={() => setIsOpen(false)} />
                 
                 <div className="absolute inset-0 pointer-events-none rounded-[2.5rem] shadow-[inset_0_0_70px_20px_rgba(85,0,0,0.7)] mix-blend-multiply" />
                 <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle,transparent_50%,rgba(0,0,0,0.6)_150%)]" />
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}

const MediaPlayer = ({ onClose }: { onClose: () => void }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(true);
  const videoRef = useRef<HTMLVideoElement>(null);

  const handleNext = (e?: React.MouseEvent) => {
    e?.stopPropagation();
    setCurrentIndex((prev) => (prev + 1) % MEDIA_ITEMS.length);
    setIsPlaying(true);
  };

  const handlePrev = (e?: React.MouseEvent) => {
    e?.stopPropagation();
    setCurrentIndex((prev) => (prev - 1 + MEDIA_ITEMS.length) % MEDIA_ITEMS.length);
    setIsPlaying(true);
  };

  const togglePlay = (e?: React.MouseEvent) => {
    e?.stopPropagation();
    if (MEDIA_ITEMS[currentIndex].type === 'video' && videoRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
      } else {
        videoRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  const currentMedia = MEDIA_ITEMS[currentIndex];

  return (
    <div className="relative w-full h-full bg-[#0a0000] flex items-center justify-center group overflow-hidden">
      
      <AnimatePresence mode="wait">
        <motion.div
          key={currentIndex}
          initial={{ opacity: 0, filter: 'blur(10px)' }}
          animate={{ opacity: 1, filter: 'blur(0px)' }}
          exit={{ opacity: 0, filter: 'blur(10px)' }}
          transition={{ duration: 1.2, ease: "easeInOut" }}
          className="w-full h-full absolute inset-0 flex items-center justify-center"
        >
          {currentMedia.type === 'video' ? (
            <video
              ref={videoRef}
              className="w-full h-full object-contain opacity-90 transition-opacity duration-1000 group-hover:opacity-100"
              src={currentMedia.src}
              autoPlay
              loop
              muted
              playsInline
            />
          ) : (
            <motion.img
              // Subtle slow zoom-in for images to keep them feeling alive (Ken Burns effect)
              animate={{ scale: [1, 1.05] }}
              transition={{ duration: 25, ease: "linear", repeat: Infinity, repeatType: 'reverse' }}
              className="w-full h-full object-contain opacity-90 transition-opacity duration-1000 group-hover:opacity-100"
              src={currentMedia.src}
              alt="A frozen moment"
            />
          )}
        </motion.div>
      </AnimatePresence>

      {/* Controls Overlay */}
      <div className="absolute inset-0 flex flex-col justify-between p-4 md:p-8 pointer-events-none z-20">
        
        {/* Top: Counter & Close */}
        <div className="flex justify-between items-center w-full">
           <div className="text-[#E8DCC4]/60 font-serif tracking-[0.3em] text-xs px-4 drop-shadow-md">
             {currentIndex + 1} / {MEDIA_ITEMS.length}
           </div>
           <button
             onClick={(e) => {
               e.stopPropagation();
               onClose();
             }}
             className="pointer-events-auto text-[#E8DCC4]/60 hover:text-[#E8DCC4] transition-all p-2 hover:rotate-90 hover:scale-110 duration-500 ease-out"
           >
             <svg width="36" height="36" viewBox="0 0 100 100" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" className="drop-shadow-lg">
               <path d="M25 30 C 45 45 55 55 75 70 M70 25 C 55 45 45 55 30 75" />
             </svg>
           </button>
        </div>
        
        {/* Hidden Click Zones for Left/Right Navigation */}
        <div className="absolute inset-y-16 left-0 w-1/3 pointer-events-auto cursor-pointer flex items-center group/left" onClick={handlePrev}>
           <div className="ml-4 opacity-0 group-hover/left:opacity-100 transition-opacity duration-500 text-[#E8DCC4]/70">
             <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><path d="M15 18l-6-6 6-6"/></svg>
           </div>
        </div>
        
        <div className="absolute inset-y-16 right-0 w-1/3 pointer-events-auto cursor-pointer flex items-center justify-end group/right" onClick={handleNext}>
           <div className="mr-4 opacity-0 group-hover/right:opacity-100 transition-opacity duration-500 text-[#E8DCC4]/70">
             <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"><path d="M9 18l6-6-6-6"/></svg>
           </div>
        </div>

        {/* Center Click Zone for Pause/Play (Only videos) */}
        {currentMedia.type === 'video' && (
          <div className="absolute inset-x-1/3 inset-y-16 pointer-events-auto cursor-pointer flex items-end justify-center" onClick={togglePlay}>
            <div className="mb-4 opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none">
              <button
                className="w-14 h-14 md:w-16 md:h-16 rounded-full bg-[#550000]/60 border border-[#E8DCC4]/20 backdrop-blur-md flex items-center justify-center text-[#E8DCC4] shadow-[0_0_30px_rgba(85,0,0,0.8)]"
              >
                {isPlaying ? (
                   <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor">
                     <rect x="6" y="4" width="4" height="16" rx="1" />
                     <rect x="14" y="4" width="4" height="16" rx="1" />
                   </svg>
                ) : (
                   <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor" className="ml-1">
                     <path d="M6 4l14 8-14 8z" />
                   </svg>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
